services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

  redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${REDIS_TOKEN}
      SRH_CONNECTION_STRING: redis://redis:6379
    depends_on:
      - redis

volumes:
  pgdata:
  cache:
